#!/bin/sh

# NOTE -- http://www.wordfind.com/solver/ (or any Scrabble cheater) may be a better alternative to this

./anagram.pl $1 $2 </usr/share/dict/words | perl -e 'print sort {length($a) <=> length($b) or $a cmp $b} grep {!/[A-Z]/} <>'
