#!/usr/bin/bash

# This drops a mirror in the same directory that this script is located in.

THIS_DIR=$( dirname $( readlink -f "$0" ) )

mkdir -p "$THIS_DIR/mirror"

minicpan -l "$THIS_DIR/mirror/"
